/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_fan87_javainjector_JavaInjector */

#ifndef _Included_me_fan87_javainjector_JavaInjector
#define _Included_me_fan87_javainjector_JavaInjector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_fan87_javainjector_JavaInjector
 * Method:    injectNativeLib
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_me_fan87_javainjector_JavaInjector_injectNativeLib
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
