/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_fan87_javainjector_JNIBinding */

#ifndef _Included_me_fan87_javainjector_JNIBinding
#define _Included_me_fan87_javainjector_JNIBinding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_fan87_javainjector_JNIBinding
 * Method:    getField
 * Signature: (Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_me_fan87_javainjector_JNIBinding_getField
  (JNIEnv *, jclass, jclass, jobject, jstring);

/*
 * Class:     me_fan87_javainjector_JNIBinding
 * Method:    getStaticField
 * Signature: (Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_me_fan87_javainjector_JNIBinding_getStaticField
  (JNIEnv *, jclass, jclass, jstring);

/*
 * Class:     me_fan87_javainjector_JNIBinding
 * Method:    setField
 * Signature: (Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_me_fan87_javainjector_JNIBinding_setField
  (JNIEnv *, jclass, jclass, jobject, jstring, jobject);

/*
 * Class:     me_fan87_javainjector_JNIBinding
 * Method:    setStaticField
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_me_fan87_javainjector_JNIBinding_setStaticField
  (JNIEnv *, jclass, jclass, jstring, jobject);

/*
 * Class:     me_fan87_javainjector_JNIBinding
 * Method:    invokeMethodS
 * Signature: (Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_me_fan87_javainjector_JNIBinding_invokeMethodS
  (JNIEnv *, jclass, jclass, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     me_fan87_javainjector_JNIBinding
 * Method:    invokeStaticMethodS
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_me_fan87_javainjector_JNIBinding_invokeStaticMethodS
  (JNIEnv *, jclass, jclass, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
